# Site settings
title: serpest
tagline: Personal Website & Blog
author: serpest
email: serpest@protonmail.com
description: >-
  Here you can find some information about me, my projects and my blog posts.
url: https://serpest.github.io
twitter_username: serpest0
github_username: serpest
header_pages:
  - projects.md
  - blog.md
  - about.md
permalink: /blog/:categories/:title
collections:
  projects:
    order:
      - tidraw.md
      - musicsync.md
      - tictactoeplus.md
      - rebuk.md
      - imgselect.md
      - sudokuresolver.md

# Theme settings
minima:
  date_format: "%F"

# Build settings
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
