title: serpest
tagline: Personal Website & Blog
description: Here you can find some information about me, my projects and my blog posts

url: https://serpest.github.io

author: serpest
email: serpest@protonmail.com
twitter_username: serpest0
github_username: serpest

header_pages:
  - projects.md
  - blog.md
  - about.md
permalink: /blog/:categories/:title
collections:
  projects:
    order:
      - tidraw.md
      - musicsync.md
      - tictactoeplus.md
      - rebuk.md
      - imgselect.md
      - sudokuresolver.md

settings:
  date_format: "%F"

plugins:
  - jekyll-feed
  - jekyll-sitemap
