title: serpest
email: serpest@protonmail.com
logo: /assets/img/profilePicture.png
description: Young self-taught in programming.
twitter_username: serpest0
github_username: serpest
theme: jekyll-theme-minimal